#!/bin/sh

install:
	sudo chmod 777 /var/www
	sudo cp config.php /var/www/
	sudo cp index.php /var/www/
	sudo cp log.php /var/www/
	sudo cp jquery-1.6.4.min.js /var/www/
	sudo cp jquery.timers-1.2.js /var/www/

uninstall:
	sudo rm /var/www/*
